import JSZip from 'jszip';
import type { ProjectFile } from './types';

/**
 * Export a project as a downloadable ZIP. The ZIP contains the raw files
 * plus a simple README so the user knows how to run it locally.
 */
export async function exportProjectAsZip(
  projectName: string,
  files: ProjectFile[]
): Promise<Blob> {
  const zip = new JSZip();

  for (const f of files) {
    zip.file(f.path, f.content);
  }

  const isMultiFile = files.length > 1;
  const hasHtmlEntry = files.some((f) => f.path === 'index.html');

  const readme = `# ${projectName}

Built with [Alizen](https://github.com/mykrwt/alizen) — the free, forever AI app builder.

## How to run

${
  hasHtmlEntry
    ? `Just open \`index.html\` in your browser, or serve locally:

\`\`\`bash
# Python
python3 -m http.server 5173

# Node (if you have npx)
npx serve .
\`\`\``
    : 'Run the project using your preferred toolchain for the included files.'
}

${isMultiFile ? 'This project has multiple files — serve over HTTP (not file://) for best results.' : ''}

## Deploy

Deploy anywhere static sites are hosted:

- **Vercel** (free): push to GitHub and import, or run \`npx vercel\`
- **Netlify** (free): drag-and-drop the project folder at https://app.netlify.com/drop
- **Cloudflare Pages**: connect your GitHub repo
- **GitHub Pages**: push to a repo and enable Pages

---
Generated by Alizen — free, open-source, zero-cost infrastructure.
`;

  zip.file('README.md', readme);

  // Add a simple vercel.json so "Deploy to Vercel" works out of the box
  if (hasHtmlEntry) {
    zip.file(
      'vercel.json',
      JSON.stringify(
        {
          cleanUrls: true,
          framework: null,
        },
        null,
        2
      )
    );
  }

  return zip.generateAsync({ type: 'blob' });
}

export function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
